### ISSUE TITLE
inserting stationId twice

### ISSUE THREAD

**Issue by interbiznw** [gablau/weather-underground-node#5]
any idea why if this is ran more than once, no matter the time limit I get this error? Only works on the first request

![image](https://user-images.githubusercontent.com/16450422/88533789-ad353200-cfbb-11ea-97b3-5125d7fa6f11.png)

second time it runs, there are 2 stationId 's in the URL request.

**Comment by gablau** [comment]
hi,
please show me the code that generates this error, otherwise I can't help you.

**Comment by interbiznw** [comment]
@gablau 

![image](https://user-images.githubusercontent.com/16450422/88690439-84db2f80-d0b0-11ea-8bfe-83c75c6db697.png)
![image](https://user-images.githubusercontent.com/16450422/88690631-b5bb6480-d0b0-11ea-91fc-0c089e7a187f.png)


Thanks for any help or guidance you can give

**Comment by interbiznw** [comment]
any ideas??

**Comment by interbiznw** [comment]
Still have not figured this out

**Comment by gablau** [comment]
Fixed on release [1.0.0](https://github.com/gablau/weather-underground-node/releases/tag/1.0.0)
